[
  "app/tests/test_config_validation.py::test_settings_defaults",
  "app/tests/test_pattern_scan.py::test_score_returns_valid_result",
  "app/tests/test_reference_mode.py::test_general_reference_like_shape_scores_reasonably",
  "app/tests/test_reference_mode.py::test_reference_coin_passes_on_reference_window",
  "app/tests/test_resolution_and_age.py::test_age_days_from_history_uses_first_candle",
  "app/tests/test_resolution_and_age.py::test_resolve_symbol_prefers_better_ranked_exact_match",
  "app/tests/test_scan_references_end_to_end.py::test_explicit_reference_symbols_are_evaluated",
  "app/tests/test_startup_import.py::test_app_import"
]